In [ ]:
import sklearn as sk
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder, MinMaxScaler,Binarizer

In [ ]:
df = pd.read_csv(r'converted_data.csv')
df

    Color    Size       City  Price Purchased
0     Red   Small      Delhi    120       Yes
1    Blue  Medium     Mumbai    150        No
2   Green   Large  Bangalore     80       Yes
3    Blue   Small      Delhi    200       Yes
4     Red  Medium    Chennai    130        No
5   Green   Large     Mumbai     95        No
6    Blue   Small  Bangalore    170       Yes
7     Red   Large    Chennai    220       Yes
8     Red   Small      Delhi    125       Yes
9    Blue   Large     Mumbai    180       Yes
10  Green  Medium  Bangalore     90        No
11    Red   Large    Chennai    210       Yes
12   Blue   Small     Mumbai    140        No
13  Green   Large      Delhi    100       Yes
14    Red  Medium  Bangalore    135       Yes
15   Blue  Medium    Chennai    160        No
16  Green   Small     Mumbai     85       Yes
17    Red   Large  Bangalore    230        No

In [ ]:
df.shape

(18, 5)

In [ ]:
df.columns

Index(['Color', 'Size', 'City', 'Price', 'Purchased'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Color      18 non-null     object
 1   Size       18 non-null     object
 2   City       18 non-null     object
 3   Price      18 non-null     int64
 4   Purchased  18 non-null     object
dtypes: int64(1), object(4)
memory usage: 852.0+ bytes

   Color    Size       City  Price Purchased
0    Red   Small      Delhi    120       Yes
1   Blue  Medium     Mumbai    150        No
2  Green   Large  Bangalore     80       Yes
3   Blue   Small      Delhi    200       Yes
4    Red  Medium    Chennai    130        No

    Color    Size       City  Price Purchased
13  Green   Large      Delhi    100       Yes
14    Red  Medium  Bangalore    135       Yes
15   Blue  Medium    Chennai    160        No
16  Green   Small     Mumbai     85       Yes
17    Red   Large  Bangalore    230        No

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0])

array(['Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No'], dtype=object)

      0    1
0   0.0  1.0
1   1.0  0.0
2   0.0  1.0
3   0.0  1.0
4   1.0  0.0
5   1.0  0.0
6   0.0  1.0
7   0.0  1.0
8   0.0  1.0
9   0.0  1.0
10  1.0  0.0
11  0.0  1.0
12  1.0  0.0
13  0.0  1.0
14  0.0  1.0
15  1.0  0.0
16  0.0  1.0
17  1.0  0.0

      0    1    2
0   0.0  0.0  1.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   1.0  0.0  0.0
4   0.0  0.0  1.0
5   0.0  1.0  0.0
6   1.0  0.0  0.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   1.0  0.0  0.0
10  0.0  1.0  0.0
11  0.0  0.0  1.0
12  1.0  0.0  0.0
13  0.0  1.0  0.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  0.0  1.0  0.0
17  0.0  0.0  1.0

   c1  c2
0   1  12
1   2  87
2   3  65
3   4  54
4   5  99

array([[0.        , 0.        ],
       [0.25      , 0.86206897],
       [0.5       , 0.6091954 ],
       [0.75      , 0.48275862],
       [1.        , 1.        ]])

array([[ 1,  2,  3,  4,  5],
       [12, 87, 65, 54, 99],
       [70, 54, 40, 11, 65]])

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])